/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstaRouteImport } from './routes/insta'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as BusinessChatbotRouteImport } from './routes/business-chatbot'
import { Route as AntiRouteImport } from './routes/anti'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as AntiIndexRouteImport } from './routes/anti.index'
import { Route as InstaSetupWizardRouteImport } from './routes/insta.setup-wizard'
import { Route as InstaProfileSetupRouteImport } from './routes/insta.profile-setup'
import { Route as InstaInventoryRouteImport } from './routes/insta.inventory'
import { Route as InstaGoalsRouteImport } from './routes/insta.goals'
import { Route as InstaAnalyzerRouteImport } from './routes/insta.analyzer'
import { Route as CustomersToolsRouteImport } from './routes/customers.tools'
import { Route as CustomersReportsRouteImport } from './routes/customers.reports'
import { Route as CustomersLedgerRouteImport } from './routes/customers.ledger'
import { Route as CustomersCustomersRouteImport } from './routes/customers.customers'
import { Route as AntiSuppliersRouteImport } from './routes/anti.suppliers'
import { Route as AntiPaymentsRouteImport } from './routes/anti.payments'
import { Route as AntiComparisonRouteImport } from './routes/anti.comparison'
import { Route as AntiCalendarRouteImport } from './routes/anti.calendar'
import { Route as AntiSuppliersIdRouteImport } from './routes/anti.suppliers.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstaRoute = InstaRouteImport.update({
  id: '/insta',
  path: '/insta',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessChatbotRoute = BusinessChatbotRouteImport.update({
  id: '/business-chatbot',
  path: '/business-chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const AntiRoute = AntiRouteImport.update({
  id: '/anti',
  path: '/anti',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersRoute,
} as any)
const AntiIndexRoute = AntiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AntiRoute,
} as any)
const InstaSetupWizardRoute = InstaSetupWizardRouteImport.update({
  id: '/setup-wizard',
  path: '/setup-wizard',
  getParentRoute: () => InstaRoute,
} as any)
const InstaProfileSetupRoute = InstaProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => InstaRoute,
} as any)
const InstaInventoryRoute = InstaInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => InstaRoute,
} as any)
const InstaGoalsRoute = InstaGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => InstaRoute,
} as any)
const InstaAnalyzerRoute = InstaAnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => InstaRoute,
} as any)
const CustomersToolsRoute = CustomersToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersReportsRoute = CustomersReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersLedgerRoute = CustomersLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersCustomersRoute = CustomersCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => CustomersRoute,
} as any)
const AntiSuppliersRoute = AntiSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AntiRoute,
} as any)
const AntiPaymentsRoute = AntiPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AntiRoute,
} as any)
const AntiComparisonRoute = AntiComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => AntiRoute,
} as any)
const AntiCalendarRoute = AntiCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AntiRoute,
} as any)
const AntiSuppliersIdRoute = AntiSuppliersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AntiSuppliersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anti': typeof AntiRouteWithChildren
  '/business-chatbot': typeof BusinessChatbotRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/insta': typeof InstaRouteWithChildren
  '/login': typeof LoginRoute
  '/anti/calendar': typeof AntiCalendarRoute
  '/anti/comparison': typeof AntiComparisonRoute
  '/anti/payments': typeof AntiPaymentsRoute
  '/anti/suppliers': typeof AntiSuppliersRouteWithChildren
  '/customers/customers': typeof CustomersCustomersRoute
  '/customers/ledger': typeof CustomersLedgerRoute
  '/customers/reports': typeof CustomersReportsRoute
  '/customers/tools': typeof CustomersToolsRoute
  '/insta/analyzer': typeof InstaAnalyzerRoute
  '/insta/goals': typeof InstaGoalsRoute
  '/insta/inventory': typeof InstaInventoryRoute
  '/insta/profile-setup': typeof InstaProfileSetupRoute
  '/insta/setup-wizard': typeof InstaSetupWizardRoute
  '/anti/': typeof AntiIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/anti/suppliers/$id': typeof AntiSuppliersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business-chatbot': typeof BusinessChatbotRoute
  '/dashboard': typeof DashboardRoute
  '/insta': typeof InstaRouteWithChildren
  '/login': typeof LoginRoute
  '/anti/calendar': typeof AntiCalendarRoute
  '/anti/comparison': typeof AntiComparisonRoute
  '/anti/payments': typeof AntiPaymentsRoute
  '/anti/suppliers': typeof AntiSuppliersRouteWithChildren
  '/customers/customers': typeof CustomersCustomersRoute
  '/customers/ledger': typeof CustomersLedgerRoute
  '/customers/reports': typeof CustomersReportsRoute
  '/customers/tools': typeof CustomersToolsRoute
  '/insta/analyzer': typeof InstaAnalyzerRoute
  '/insta/goals': typeof InstaGoalsRoute
  '/insta/inventory': typeof InstaInventoryRoute
  '/insta/profile-setup': typeof InstaProfileSetupRoute
  '/insta/setup-wizard': typeof InstaSetupWizardRoute
  '/anti': typeof AntiIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/anti/suppliers/$id': typeof AntiSuppliersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anti': typeof AntiRouteWithChildren
  '/business-chatbot': typeof BusinessChatbotRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/insta': typeof InstaRouteWithChildren
  '/login': typeof LoginRoute
  '/anti/calendar': typeof AntiCalendarRoute
  '/anti/comparison': typeof AntiComparisonRoute
  '/anti/payments': typeof AntiPaymentsRoute
  '/anti/suppliers': typeof AntiSuppliersRouteWithChildren
  '/customers/customers': typeof CustomersCustomersRoute
  '/customers/ledger': typeof CustomersLedgerRoute
  '/customers/reports': typeof CustomersReportsRoute
  '/customers/tools': typeof CustomersToolsRoute
  '/insta/analyzer': typeof InstaAnalyzerRoute
  '/insta/goals': typeof InstaGoalsRoute
  '/insta/inventory': typeof InstaInventoryRoute
  '/insta/profile-setup': typeof InstaProfileSetupRoute
  '/insta/setup-wizard': typeof InstaSetupWizardRoute
  '/anti/': typeof AntiIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/anti/suppliers/$id': typeof AntiSuppliersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anti'
    | '/business-chatbot'
    | '/customers'
    | '/dashboard'
    | '/insta'
    | '/login'
    | '/anti/calendar'
    | '/anti/comparison'
    | '/anti/payments'
    | '/anti/suppliers'
    | '/customers/customers'
    | '/customers/ledger'
    | '/customers/reports'
    | '/customers/tools'
    | '/insta/analyzer'
    | '/insta/goals'
    | '/insta/inventory'
    | '/insta/profile-setup'
    | '/insta/setup-wizard'
    | '/anti/'
    | '/customers/'
    | '/anti/suppliers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business-chatbot'
    | '/dashboard'
    | '/insta'
    | '/login'
    | '/anti/calendar'
    | '/anti/comparison'
    | '/anti/payments'
    | '/anti/suppliers'
    | '/customers/customers'
    | '/customers/ledger'
    | '/customers/reports'
    | '/customers/tools'
    | '/insta/analyzer'
    | '/insta/goals'
    | '/insta/inventory'
    | '/insta/profile-setup'
    | '/insta/setup-wizard'
    | '/anti'
    | '/customers'
    | '/anti/suppliers/$id'
  id:
    | '__root__'
    | '/'
    | '/anti'
    | '/business-chatbot'
    | '/customers'
    | '/dashboard'
    | '/insta'
    | '/login'
    | '/anti/calendar'
    | '/anti/comparison'
    | '/anti/payments'
    | '/anti/suppliers'
    | '/customers/customers'
    | '/customers/ledger'
    | '/customers/reports'
    | '/customers/tools'
    | '/insta/analyzer'
    | '/insta/goals'
    | '/insta/inventory'
    | '/insta/profile-setup'
    | '/insta/setup-wizard'
    | '/anti/'
    | '/customers/'
    | '/anti/suppliers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntiRoute: typeof AntiRouteWithChildren
  BusinessChatbotRoute: typeof BusinessChatbotRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  InstaRoute: typeof InstaRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insta': {
      id: '/insta'
      path: '/insta'
      fullPath: '/insta'
      preLoaderRoute: typeof InstaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-chatbot': {
      id: '/business-chatbot'
      path: '/business-chatbot'
      fullPath: '/business-chatbot'
      preLoaderRoute: typeof BusinessChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anti': {
      id: '/anti'
      path: '/anti'
      fullPath: '/anti'
      preLoaderRoute: typeof AntiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/anti/': {
      id: '/anti/'
      path: '/'
      fullPath: '/anti/'
      preLoaderRoute: typeof AntiIndexRouteImport
      parentRoute: typeof AntiRoute
    }
    '/insta/setup-wizard': {
      id: '/insta/setup-wizard'
      path: '/setup-wizard'
      fullPath: '/insta/setup-wizard'
      preLoaderRoute: typeof InstaSetupWizardRouteImport
      parentRoute: typeof InstaRoute
    }
    '/insta/profile-setup': {
      id: '/insta/profile-setup'
      path: '/profile-setup'
      fullPath: '/insta/profile-setup'
      preLoaderRoute: typeof InstaProfileSetupRouteImport
      parentRoute: typeof InstaRoute
    }
    '/insta/inventory': {
      id: '/insta/inventory'
      path: '/inventory'
      fullPath: '/insta/inventory'
      preLoaderRoute: typeof InstaInventoryRouteImport
      parentRoute: typeof InstaRoute
    }
    '/insta/goals': {
      id: '/insta/goals'
      path: '/goals'
      fullPath: '/insta/goals'
      preLoaderRoute: typeof InstaGoalsRouteImport
      parentRoute: typeof InstaRoute
    }
    '/insta/analyzer': {
      id: '/insta/analyzer'
      path: '/analyzer'
      fullPath: '/insta/analyzer'
      preLoaderRoute: typeof InstaAnalyzerRouteImport
      parentRoute: typeof InstaRoute
    }
    '/customers/tools': {
      id: '/customers/tools'
      path: '/tools'
      fullPath: '/customers/tools'
      preLoaderRoute: typeof CustomersToolsRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/reports': {
      id: '/customers/reports'
      path: '/reports'
      fullPath: '/customers/reports'
      preLoaderRoute: typeof CustomersReportsRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/ledger': {
      id: '/customers/ledger'
      path: '/ledger'
      fullPath: '/customers/ledger'
      preLoaderRoute: typeof CustomersLedgerRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/customers': {
      id: '/customers/customers'
      path: '/customers'
      fullPath: '/customers/customers'
      preLoaderRoute: typeof CustomersCustomersRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/anti/suppliers': {
      id: '/anti/suppliers'
      path: '/suppliers'
      fullPath: '/anti/suppliers'
      preLoaderRoute: typeof AntiSuppliersRouteImport
      parentRoute: typeof AntiRoute
    }
    '/anti/payments': {
      id: '/anti/payments'
      path: '/payments'
      fullPath: '/anti/payments'
      preLoaderRoute: typeof AntiPaymentsRouteImport
      parentRoute: typeof AntiRoute
    }
    '/anti/comparison': {
      id: '/anti/comparison'
      path: '/comparison'
      fullPath: '/anti/comparison'
      preLoaderRoute: typeof AntiComparisonRouteImport
      parentRoute: typeof AntiRoute
    }
    '/anti/calendar': {
      id: '/anti/calendar'
      path: '/calendar'
      fullPath: '/anti/calendar'
      preLoaderRoute: typeof AntiCalendarRouteImport
      parentRoute: typeof AntiRoute
    }
    '/anti/suppliers/$id': {
      id: '/anti/suppliers/$id'
      path: '/$id'
      fullPath: '/anti/suppliers/$id'
      preLoaderRoute: typeof AntiSuppliersIdRouteImport
      parentRoute: typeof AntiSuppliersRoute
    }
  }
}

interface AntiSuppliersRouteChildren {
  AntiSuppliersIdRoute: typeof AntiSuppliersIdRoute
}

const AntiSuppliersRouteChildren: AntiSuppliersRouteChildren = {
  AntiSuppliersIdRoute: AntiSuppliersIdRoute,
}

const AntiSuppliersRouteWithChildren = AntiSuppliersRoute._addFileChildren(
  AntiSuppliersRouteChildren,
)

interface AntiRouteChildren {
  AntiCalendarRoute: typeof AntiCalendarRoute
  AntiComparisonRoute: typeof AntiComparisonRoute
  AntiPaymentsRoute: typeof AntiPaymentsRoute
  AntiSuppliersRoute: typeof AntiSuppliersRouteWithChildren
  AntiIndexRoute: typeof AntiIndexRoute
}

const AntiRouteChildren: AntiRouteChildren = {
  AntiCalendarRoute: AntiCalendarRoute,
  AntiComparisonRoute: AntiComparisonRoute,
  AntiPaymentsRoute: AntiPaymentsRoute,
  AntiSuppliersRoute: AntiSuppliersRouteWithChildren,
  AntiIndexRoute: AntiIndexRoute,
}

const AntiRouteWithChildren = AntiRoute._addFileChildren(AntiRouteChildren)

interface CustomersRouteChildren {
  CustomersCustomersRoute: typeof CustomersCustomersRoute
  CustomersLedgerRoute: typeof CustomersLedgerRoute
  CustomersReportsRoute: typeof CustomersReportsRoute
  CustomersToolsRoute: typeof CustomersToolsRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomersRoute: CustomersCustomersRoute,
  CustomersLedgerRoute: CustomersLedgerRoute,
  CustomersReportsRoute: CustomersReportsRoute,
  CustomersToolsRoute: CustomersToolsRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface InstaRouteChildren {
  InstaAnalyzerRoute: typeof InstaAnalyzerRoute
  InstaGoalsRoute: typeof InstaGoalsRoute
  InstaInventoryRoute: typeof InstaInventoryRoute
  InstaProfileSetupRoute: typeof InstaProfileSetupRoute
  InstaSetupWizardRoute: typeof InstaSetupWizardRoute
}

const InstaRouteChildren: InstaRouteChildren = {
  InstaAnalyzerRoute: InstaAnalyzerRoute,
  InstaGoalsRoute: InstaGoalsRoute,
  InstaInventoryRoute: InstaInventoryRoute,
  InstaProfileSetupRoute: InstaProfileSetupRoute,
  InstaSetupWizardRoute: InstaSetupWizardRoute,
}

const InstaRouteWithChildren = InstaRoute._addFileChildren(InstaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntiRoute: AntiRouteWithChildren,
  BusinessChatbotRoute: BusinessChatbotRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DashboardRoute: DashboardRoute,
  InstaRoute: InstaRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
